# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Mayank Ambaliya Home Page"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "Mayank Ambaliya"

# Tagline section text
tagline: >-
    Senior Software Engineer working in Amazon Web Services developing Cryptography APIs and SDKs. Loves travelling, hiking, and spending time with my kid.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-solid fa-file"
      text: "Resume"
      url: "https://mayankambaliya.github.io/mayank.me/resume.pdf"
      alt: "Mayank Ambaliya Resume"
      title: "Mayank Ambaliya's Resume"
      target: "_blank"
  - link:
      icon: "fa-brands fa-linkedin"
      text: "LinkedIn"
      url: "https://linkedin.com/in/mayankambaliya"
      alt: "Mayank Ambaliya LinkedIn"
      title: "Mayank Ambaliya's LinkedIn"
      target: "_blank"

# Footer text
footer: >
    Hi there! Interested in talking about Cryptography or building web services/SDKs, connect with me on LinkedIn.
